# -*- coding: utf-8 -*-
"""Makrov Chain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQGEA_Pf8aI5OdfBn7CFIzl2i01IAbSo
"""

import random
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))
with open(filename, "r", encoding="utf-8", errors="ignore") as f:
    text = f.read()

print(f"\nTraining text loaded. Length: {len(text)} characters\n")

order = int(input("Enter Markov chain order (e.g., 1, 2, 3, 4, 5): "))
print(f"\nUsing Markov chain order: {order}\n")

markov_chain = {}

for i in range(len(text) - order):
    state = text[i:i+order]
    next_char = text[i+order]

    if state not in markov_chain:
        markov_chain[state] = []

    markov_chain[state].append(next_char)

print(f"Model built. Unique states: {len(markov_chain)}\n")

def generate_text(length=300):
    state = random.choice(list(markov_chain.keys()))
    output = state

    for _ in range(length):
        if state not in markov_chain:
            break
        next_char = random.choice(markov_chain[state])
        output += next_char
        state = output[-order:]
    return output

print("Generated Text:\n")
print(generate_text(400))

